import { makeActionCreator } from '../utility';

export const CHECKOUT_PHASE = {
  ERROR: 'ERROR',
  SUCCESS: 'SUCCESS',
  CREDIT_VALIDATION: 'CREDIT_VALIDATION',
  QUANTITY_VERIFICATION: 'QUANTITY_VERIFICATION',
  PURCHASE_FINALIZATION: 'PURCHASE_FINALIZATION',
};
export const SET_CHECKOUT_PHASE = 'SET_CHECKOUT_PHASE';
export const setCheckoutPhase = makeActionCreator(SET_CHECKOUT_PHASE, 'phase');
